export const countryCodes = [
  { country: 'Albania', code: 'AL', image: 'albania' },
  { country: 'Australia', code: 'AU', image: 'australia' },
  { country: 'Austria', code: 'AT', image: 'austria' },
  { country: 'Belgium', code: 'BE', image: 'belgium' },
  { country: 'Brazil', code: 'BR', image: 'brazil' },
  { country: 'Bangladesh', code: 'BD', image: 'bangladesh' },
  { country: 'Bulgaria', code: 'BG', image: 'bulgaria' },
  { country: 'Canada', code: 'CA', image: 'canada' },
  { country: 'Colombia', code: 'CO', image: 'colombia' },
  { country: 'Croatia', code: 'HR', image: 'croatia' },
  { country: 'Cyprus', code: 'CY', image: 'cyprus' },
  { country: 'Czech Republic', code: 'CZ', image: 'czech-republic' },
  { country: 'Denmark', code: 'DK', image: 'denmark' },
  { country: 'Estonia', code: 'EE', image: 'estonia' },
  { country: 'Finland', code: 'FI', image: 'finland' },
  { country: 'France', code: 'FR', image: 'france' },
  { country: 'Germany', code: 'DE', image: 'germany' },
  { country: 'Ghana', code: 'GH', image: 'ghana' },
  { country: 'Gibraltar', code: 'GI', image: 'gibraltar' },
  { country: 'Greece', code: 'GR', image: 'greece' },
  { country: 'Hong Kong', code: 'HK', image: 'hong-kong' },
  { country: 'Hungary', code: 'HU', image: 'hungary' },
  { country: 'India', code: 'IN', image: 'india' },
  //{ country: 'Indonesia', code: 'ID', image: 'indonesia'}, invite only
  { country: 'Ireland', code: 'IE', image: 'ireland' },
  { country: 'Italy', code: 'IT', image: 'italy' },
  { country: 'Japan', code: 'JP', image: 'japan' },
  { country: 'Jordan', code: 'JO', image: 'jordan' },
  { country: 'Kenya', code: 'KE', image: 'kenya' },
  { country: 'Latvia', code: 'LV', image: 'latvia' },
  { country: 'Liechtenstein', code: 'LI', image: 'liechtenstein' },
  { country: 'Lithuania', code: 'LT', image: 'lithuania' },
  { country: 'Luxembourg', code: 'LU', image: 'luxembourg' },
  { country: 'Malaysia', code: 'MY', image: 'malaysia' },
  { country: 'Malta', code: 'MT', image: 'malta' },
  { country: 'Mexico ', code: 'MX', image: 'mexico' },
  { country: 'Netherlands', code: 'NL', image: 'netherlands' },
  { country: 'New Zealand', code: 'NZ', image: 'new-zealand' },
  { country: 'Nigeria', code: 'NG', image: 'nigeria' },
  { country: 'Norway', code: 'NO', image: 'norway' },
  { country: 'Pakistan', code: 'PK', image: 'pakistan' },
  { country: 'Philippines', code: 'PH', image: 'philippine' },
  { country: 'Poland', code: 'PL', image: 'poland' },
  { country: 'Portugal', code: 'PT', image: 'portugal' },
  { country: 'Romania', code: 'RO', image: 'romania' },
  { country: 'Singapore', code: 'SG', image: 'singapore' },
  { country: 'Slovakia', code: 'SK', image: 'slovakia' },
  { country: 'Slovenia', code: 'SI', image: 'slovenia' },
  { country: 'South Africa', code: 'ZA', image: 'south-africa' },
  { country: 'Spain', code: 'ES', image: 'spain' },
  { country: 'Sweden', code: 'SE', image: 'sweden' },
  { country: 'Switzerland', code: 'CH', image: 'switzerland' },
  { country: 'Thailand', code: 'TH', image: 'thailand' },
  { country: 'Turkey', code: 'TR', image: 'turkey' },
  { country: 'United Arab Emirates', code: 'AE', image: 'united-arab-emirates' },
  { country: 'United Kingdom', code: 'GB', image: 'united-kingdom' },
  { country: 'United States', code: 'US', image: 'united-states-of-america' },
]

export const countryCurrencies = [
  { currency: 'Australian Dollar', symbol: 'A$', code: 'AUD', countries: ['AU'] },
  { currency: 'Albanian Lek', symbol: 'Lek', code: 'ALL', countries: ['AL'] },
  {
    currency: 'Euro',
    symbol: '€',
    code: 'EUR',
    countries: [
      'AT',
      'BE',
      'CY',
      'EE',
      'FI',
      'FR',
      'DE',
      'GR',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MT',
      'NL',
      'PT',
      'SK',
      'SI',
      'ES',
    ],
  },
  { currency: 'Bangladeshi Taka', symbol: '৳', code: 'BDT', countries: ['BD'] },
  { currency: 'Brazilian Real', symbol: 'R$', code: 'BRL', countries: ['BR'] },
  { currency: 'Bulgarian Lev', symbol: 'лв', code: 'BGN', countries: ['BG'] },
  { currency: 'Canadian Dollar', symbol: 'C$', code: 'CAD', countries: ['CA'] },
  { currency: 'Colombian Peso', symbol: '$', code: 'COP', countries: ['CO'] },
  { currency: 'Croatian Kuna', symbol: 'kn', code: 'HRK', countries: ['HR'] },
  { currency: 'Czech Koruna', symbol: 'Kč', code: 'CZK', countries: ['CZ'] },
  { currency: 'Danish Krone', symbol: 'kr', code: 'DKK', countries: ['DK'] },
  { currency: 'Ghanaian Cedi', symbol: '₵', code: 'GHS', countries: ['GH'] },
  { currency: 'Gibraltar Pound', symbol: '£', code: 'GIP', countries: ['GI'] },
  { currency: 'Hong Kong Dollar', symbol: 'HK$', code: 'HKD', countries: ['HK'] },
  { currency: 'Hungarian Forint', symbol: 'Ft', code: 'HUF', countries: ['HU'] },
  { currency: 'Indian Rupee', symbol: '₹', code: 'INR', countries: ['IN'] },
  { currency: 'Japanese Yen', symbol: '¥', code: 'JPY', countries: ['JP'] },
  { currency: 'Kenyan Shilling', symbol: 'KSh', code: 'KES', countries: ['KE'] },
  { currency: 'Swiss Franc', symbol: 'CHF', code: 'CHF', countries: ['LI', 'CH'] },
  { currency: 'Malaysian Ringgit', symbol: 'RM', code: 'MYR', countries: ['MY'] },
  { currency: 'Mexican Peso', symbol: '$', code: 'MXN', countries: ['MX'] },
  { currency: 'New Zealand Dollar', symbol: 'NZ$', code: 'NZD', countries: ['NZ'] },
  { currency: 'Nigerian Naira', symbol: '₦', code: 'NGN', countries: ['NG'] },
  { currency: 'Norwegian Krone', symbol: 'kr', code: 'NOK', countries: ['NO'] },
  { currency: 'Philippine Peso', symbol: '₱', code: 'PHP', countries: ['PH'] },
  { currency: 'Polish Zloty', symbol: 'zł', code: 'PLN', countries: ['PL'] },
  { currency: 'Romanian Leu', symbol: 'lei', code: 'RON', countries: ['RO'] },
  { currency: 'Singapore Dollar', symbol: 'S$', code: 'SGD', countries: ['SG'] },
  { currency: 'South African Rand', symbol: 'R', code: 'ZAR', countries: ['ZA'] },
  { currency: 'Swedish Krona', symbol: 'kr', code: 'SEK', countries: ['SE'] },
  { currency: 'Thai Baht', symbol: '฿', code: 'THB', countries: ['TH'] },
  { currency: 'United Arab Emirates Dirham', symbol: 'د.إ', code: 'AED', countries: ['AE'] },
  { currency: 'British Pound', symbol: '£', code: 'GBP', countries: ['GB'] },
  { currency: 'United States Dollar', symbol: '$', code: 'USD', countries: ['US'] },
  { currency: 'Turkish Lira', symbol: '₺', code: 'TRY', countries: ['TR'] },
  { currency: 'Pakistani Rupee', symbol: '₨', code: 'PKR', countries: ['PK'] },
  { currency: 'Jordanian Dinar', symbol: 'JD', code: 'JOD', countries: ['JO'] },
]

export const countryCodesFull = [
  { country: 'Afghanistan', code: 'AF' },
  { country: 'Albania', code: 'AL' },
  { country: 'Algeria', code: 'DZ' },
  { country: 'Andorra', code: 'AD' },
  { country: 'Angola', code: 'AO' },
  { country: 'Antigua and Barbuda', code: 'AG' },
  { country: 'Argentina', code: 'AR' },
  { country: 'Armenia', code: 'AM' },
  { country: 'Australia', code: 'AU' },
  { country: 'Austria', code: 'AT' },
  { country: 'Azerbaijan', code: 'AZ' },
  { country: 'Bahamas', code: 'BS' },
  { country: 'Bahrain', code: 'BH' },
  { country: 'Bangladesh', code: 'BD' },
  { country: 'Barbados', code: 'BB' },
  { country: 'Belarus', code: 'BY' },
  { country: 'Belgium', code: 'BE' },
  { country: 'Belize', code: 'BZ' },
  { country: 'Benin', code: 'BJ' },
  { country: 'Bhutan', code: 'BT' },
  { country: 'Bolivia', code: 'BO' },
  { country: 'Bosnia and Herzegovina', code: 'BA' },
  { country: 'Botswana', code: 'BW' },
  { country: 'Brazil', code: 'BR' },
  { country: 'Brunei Darussalam', code: 'BN' },
  { country: 'Bulgaria', code: 'BG' },
  { country: 'Burkina Faso', code: 'BF' },
  { country: 'Burundi', code: 'BI' },
  { country: 'Cabo Verde', code: 'CV' },
  { country: 'Cambodia', code: 'KH' },
  { country: 'Cameroon', code: 'CM' },
  { country: 'Canada', code: 'CA' },
  { country: 'Central African Republic', code: 'CF' },
  { country: 'Chad', code: 'TD' },
  { country: 'Chile', code: 'CL' },
  { country: 'China', code: 'CN' },
  { country: 'Colombia', code: 'CO' },
  { country: 'Comoros', code: 'KM' },
  { country: 'Congo (Congo-Brazzaville)', code: 'CG' },
  { country: 'Congo, Democratic Republic of the', code: 'CD' },
  { country: 'Costa Rica', code: 'CR' },
  { country: 'Croatia', code: 'HR' },
  { country: 'Cuba', code: 'CU' },
  { country: 'Cyprus', code: 'CY' },
  { country: 'Czechia (Czech Republic)', code: 'CZ' },
  { country: 'Denmark', code: 'DK' },
  { country: 'Djibouti', code: 'DJ' },
  { country: 'Dominica', code: 'DM' },
  { country: 'Dominican Republic', code: 'DO' },
  { country: 'Ecuador', code: 'EC' },
  { country: 'Egypt', code: 'EG' },
  { country: 'El Salvador', code: 'SV' },
  { country: 'Equatorial Guinea', code: 'GQ' },
  { country: 'Eritrea', code: 'ER' },
  { country: 'Estonia', code: 'EE' },
  { country: 'Eswatini', code: 'SZ' },
  { country: 'Ethiopia', code: 'ET' },
  { country: 'Fiji', code: 'FJ' },
  { country: 'Finland', code: 'FI' },
  { country: 'France', code: 'FR' },
  { country: 'Gabon', code: 'GA' },
  { country: 'Gambia', code: 'GM' },
  { country: 'Georgia', code: 'GE' },
  { country: 'Germany', code: 'DE' },
  { country: 'Ghana', code: 'GH' },
  { country: 'Greece', code: 'GR' },
  { country: 'Grenada', code: 'GD' },
  { country: 'Guatemala', code: 'GT' },
  { country: 'Guinea', code: 'GN' },
  { country: 'Guinea-Bissau', code: 'GW' },
  { country: 'Guyana', code: 'GY' },
  { country: 'Haiti', code: 'HT' },
  { country: 'Honduras', code: 'HN' },
  { country: 'Hungary', code: 'HU' },
  { country: 'Iceland', code: 'IS' },
  { country: 'India', code: 'IN' },
  { country: 'Indonesia', code: 'ID' },
  { country: 'Iran', code: 'IR' },
  { country: 'Iraq', code: 'IQ' },
  { country: 'Ireland', code: 'IE' },
  { country: 'Israel', code: 'IL' },
  { country: 'Italy', code: 'IT' },
  { country: 'Jamaica', code: 'JM' },
  { country: 'Japan', code: 'JP' },
  { country: 'Jordan', code: 'JO' },
  { country: 'Kazakhstan', code: 'KZ' },
  { country: 'Kenya', code: 'KE' },
  { country: 'Kiribati', code: 'KI' },
  { country: 'Kuwait', code: 'KW' },
  { country: 'Kyrgyzstan', code: 'KG' },
  { country: 'Laos', code: 'LA' },
  { country: 'Latvia', code: 'LV' },
  { country: 'Lebanon', code: 'LB' },
  { country: 'Lesotho', code: 'LS' },
  { country: 'Liberia', code: 'LR' },
  { country: 'Libya', code: 'LY' },
  { country: 'Liechtenstein', code: 'LI' },
  { country: 'Lithuania', code: 'LT' },
  { country: 'Luxembourg', code: 'LU' },
  { country: 'Madagascar', code: 'MG' },
  { country: 'Malawi', code: 'MW' },
  { country: 'Malaysia', code: 'MY' },
  { country: 'Maldives', code: 'MV' },
  { country: 'Mali', code: 'ML' },
  { country: 'Malta', code: 'MT' },
  { country: 'Marshall Islands', code: 'MH' },
  { country: 'Mauritania', code: 'MR' },
  { country: 'Mauritius', code: 'MU' },
  { country: 'Mexico', code: 'MX' },
  { country: 'Micronesia', code: 'FM' },
  { country: 'Moldova', code: 'MD' },
  { country: 'Monaco', code: 'MC' },
  { country: 'Mongolia', code: 'MN' },
  { country: 'Montenegro', code: 'ME' },
  { country: 'Morocco', code: 'MA' },
  { country: 'Mozambique', code: 'MZ' },
  { country: 'Myanmar', code: 'MM' },
  { country: 'Namibia', code: 'NA' },
  { country: 'Nauru', code: 'NR' },
  { country: 'Nepal', code: 'NP' },
  { country: 'Netherlands', code: 'NL' },
  { country: 'New Zealand', code: 'NZ' },
  { country: 'Nicaragua', code: 'NI' },
  { country: 'Niger', code: 'NE' },
  { country: 'Nigeria', code: 'NG' },
  { country: 'North Korea', code: 'KP' },
  { country: 'North Macedonia', code: 'MK' },
  { country: 'Norway', code: 'NO' },
  { country: 'Oman', code: 'OM' },
  { country: 'Pakistan', code: 'PK' },
  { country: 'Palau', code: 'PW' },
  { country: 'Palestine State', code: 'PS' },
  { country: 'Panama', code: 'PA' },
  { country: 'Papua New Guinea', code: 'PG' },
  { country: 'Paraguay', code: 'PY' },
  { country: 'Peru', code: 'PE' },
  { country: 'Philippines', code: 'PH' },
  { country: 'Poland', code: 'PL' },
  { country: 'Portugal', code: 'PT' },
  { country: 'Qatar', code: 'QA' },
  { country: 'Romania', code: 'RO' },
  { country: 'Russia', code: 'RU' },
  { country: 'Rwanda', code: 'RW' },
  { country: 'Saint Kitts and Nevis', code: 'KN' },
  { country: 'Saint Lucia', code: 'LC' },
  { country: 'Saint Vincent and the Grenadines', code: 'VC' },
  { country: 'Samoa', code: 'WS' },
  { country: 'San Marino', code: 'SM' },
  { country: 'Sao Tome and Principe', code: 'ST' },
  { country: 'Saudi Arabia', code: 'SA' },
  { country: 'Senegal', code: 'SN' },
  { country: 'Serbia', code: 'RS' },
  { country: 'Seychelles', code: 'SC' },
  { country: 'Sierra Leone', code: 'SL' },
  { country: 'Singapore', code: 'SG' },
  { country: 'Slovakia', code: 'SK' },
  { country: 'Slovenia', code: 'SI' },
  { country: 'Solomon Islands', code: 'SB' },
  { country: 'Somalia', code: 'SO' },
  { country: 'South Africa', code: 'ZA' },
  { country: 'South Korea', code: 'KR' },
  { country: 'South Sudan', code: 'SS' },
  { country: 'Spain', code: 'ES' },
  { country: 'Sri Lanka', code: 'LK' },
  { country: 'Sudan', code: 'SD' },
  { country: 'Suriname', code: 'SR' },
  { country: 'Sweden', code: 'SE' },
  { country: 'Switzerland', code: 'CH' },
  { country: 'Syria', code: 'SY' },
  { country: 'Tajikistan', code: 'TJ' },
  { country: 'Tanzania', code: 'TZ' },
  { country: 'Thailand', code: 'TH' },
  { country: 'Timor-Leste', code: 'TL' },
  { country: 'Togo', code: 'TG' },
  { country: 'Tonga', code: 'TO' },
  { country: 'Trinidad and Tobago', code: 'TT' },
  { country: 'Tunisia', code: 'TN' },
  { country: 'Turkey', code: 'TR' },
  { country: 'Turkmenistan', code: 'TM' },
  { country: 'Tuvalu', code: 'TV' },
  { country: 'Uganda', code: 'UG' },
  { country: 'Ukraine', code: 'UA' },
  { country: 'United Arab Emirates', code: 'AE' },
  { country: 'United Kingdom', code: 'GB' },
  { country: 'United States of America', code: 'US' },
  { country: 'Uruguay', code: 'UY' },
  { country: 'Uzbekistan', code: 'UZ' },
  { country: 'Vanuatu', code: 'VU' },
  { country: 'Vatican City', code: 'VA' },
  { country: 'Venezuela', code: 'VE' },
  { country: 'Vietnam', code: 'VN' },
  { country: 'Yemen', code: 'YE' },
  { country: 'Zambia', code: 'ZM' },
  { country: 'Zimbabwe', code: 'ZW' },
]

export const SEPA_COUNTRIES = [
  'AT', // Austria
  'BE', // Belgium
  'BG', // Bulgaria
  'CH', // Switzerland
  'CY', // Cyprus
  'CZ', // Czech Republic
  'DE', // Germany
  'DK', // Denmark
  'EE', // Estonia
  'ES', // Spain
  'FI', // Finland
  'FR', // France
  'GB', // United Kingdom
  'GI', // Gibraltar
  'GR', // Greece
  'HR', // Croatia
  'HU', // Hungary
  'IE', // Ireland
  'IS', // Iceland
  'IT', // Italy
  'LI', // Liechtenstein
  'LT', // Lithuania
  'LU', // Luxembourg
  'LV', // Latvia
  'MC', // Monaco
  'MT', // Malta
  'NL', // Netherlands
  'NO', // Norway
  'PL', // Poland
  'PT', // Portugal
  'RO', // Romania
  'SE', // Sweden
  'SI', // Slovenia
  'SK', // Slovakia
  'SM', // San Marino
  'VA', // Vatican City
]
