/**
 * Provider-aware supported countries for payout onboarding.
 * Stripe uses the historic Connect list in country-codes.js.
 * Whop uses the payout-supported list from Whop docs.
 */
import { countryCodes as stripeCountryCodes } from './country-codes'

export type CountryOption = {
  country: string
  code: string
  image: string
}

export const whopCountryCodes: CountryOption[] = [
  { country: 'Andorra', code: 'AD', image: 'default' },
  { country: 'United Arab Emirates', code: 'AE', image: 'united-arab-emirates' },
  { country: 'Antigua and Barbuda', code: 'AG', image: 'default' },
  { country: 'Anguilla', code: 'AI', image: 'default' },
  { country: 'Albania', code: 'AL', image: 'albania' },
  { country: 'Armenia', code: 'AM', image: 'default' },
  { country: 'Netherlands Antilles', code: 'AN', image: 'default' },
  { country: 'Angola', code: 'AO', image: 'default' },
  { country: 'Antarctica', code: 'AQ', image: 'default' },
  { country: 'Argentina', code: 'AR', image: 'default' },
  { country: 'American Samoa', code: 'AS', image: 'default' },
  { country: 'Austria', code: 'AT', image: 'austria' },
  { country: 'Australia', code: 'AU', image: 'australia' },
  { country: 'Aruba', code: 'AW', image: 'default' },
  { country: 'Azerbaijan', code: 'AZ', image: 'default' },
  { country: 'Bosnia and Herzegovina', code: 'BA', image: 'default' },
  { country: 'Barbados', code: 'BB', image: 'default' },
  { country: 'Bangladesh', code: 'BD', image: 'bangladesh' },
  { country: 'Belgium', code: 'BE', image: 'belgium' },
  { country: 'Burkina Faso', code: 'BF', image: 'default' },
  { country: 'Bulgaria', code: 'BG', image: 'bulgaria' },
  { country: 'Bahrain', code: 'BH', image: 'default' },
  { country: 'Benin', code: 'BJ', image: 'default' },
  { country: 'Saint Barthélemy', code: 'BL', image: 'default' },
  { country: 'Bermuda', code: 'BM', image: 'default' },
  { country: 'Brunei', code: 'BN', image: 'default' },
  { country: 'Bolivia', code: 'BO', image: 'default' },
  { country: 'Brazil', code: 'BR', image: 'brazil' },
  { country: 'Bahamas', code: 'BS', image: 'default' },
  { country: 'Bhutan', code: 'BT', image: 'default' },
  { country: 'Botswana', code: 'BW', image: 'default' },
  { country: 'Belize', code: 'BZ', image: 'belize' },
  { country: 'Canada', code: 'CA', image: 'canada' },
  { country: 'Cocos (Keeling) Islands', code: 'CC', image: 'default' },
  { country: 'Republic of the Congo', code: 'CG', image: 'default' },
  { country: 'Switzerland', code: 'CH', image: 'switzerland' },
  { country: "Côte d'Ivoire", code: 'CI', image: 'default' },
  { country: 'Cook Islands', code: 'CK', image: 'default' },
  { country: 'Chile', code: 'CL', image: 'chile' },
  { country: 'Cameroon', code: 'CM', image: 'default' },
  { country: 'China', code: 'CN', image: 'default' },
  { country: 'Colombia', code: 'CO', image: 'colombia' },
  { country: 'Costa Rica', code: 'CR', image: 'default' },
  { country: 'Cape Verde', code: 'CV', image: 'default' },
  { country: 'Curaçao', code: 'CW', image: 'default' },
  { country: 'Christmas Island', code: 'CX', image: 'default' },
  { country: 'Cyprus', code: 'CY', image: 'cyprus' },
  { country: 'Czech Republic', code: 'CZ', image: 'czech-republic' },
  { country: 'Germany', code: 'DE', image: 'germany' },
  { country: 'Djibouti', code: 'DJ', image: 'default' },
  { country: 'Denmark', code: 'DK', image: 'denmark' },
  { country: 'Dominica', code: 'DM', image: 'default' },
  { country: 'Dominican Republic', code: 'DO', image: 'default' },
  { country: 'Algeria', code: 'DZ', image: 'default' },
  { country: 'Ecuador', code: 'EC', image: 'default' },
  { country: 'Estonia', code: 'EE', image: 'estonia' },
  { country: 'Egypt', code: 'EG', image: 'egypt' },
  { country: 'Western Sahara', code: 'EH', image: 'default' },
  { country: 'Spain', code: 'ES', image: 'spain' },
  { country: 'Ethiopia', code: 'ET', image: 'ethiopia' },
  { country: 'Finland', code: 'FI', image: 'finland' },
  { country: 'Fiji', code: 'FJ', image: 'default' },
  { country: 'Falkland Islands', code: 'FK', image: 'default' },
  { country: 'Micronesia', code: 'FM', image: 'default' },
  { country: 'Faroe Islands', code: 'FO', image: 'default' },
  { country: 'France', code: 'FR', image: 'france' },
  { country: 'Gabon', code: 'GA', image: 'default' },
  { country: 'United Kingdom', code: 'GB', image: 'united-kingdom' },
  { country: 'Grenada', code: 'GD', image: 'default' },
  { country: 'Georgia', code: 'GE', image: 'default' },
  { country: 'French Guiana', code: 'GF', image: 'default' },
  { country: 'Guernsey', code: 'GG', image: 'default' },
  { country: 'Ghana', code: 'GH', image: 'ghana' },
  { country: 'Gibraltar', code: 'GI', image: 'gibraltar' },
  { country: 'Greenland', code: 'GL', image: 'default' },
  { country: 'Gambia', code: 'GM', image: 'default' },
  { country: 'Guinea', code: 'GN', image: 'default' },
  { country: 'Guadeloupe', code: 'GP', image: 'default' },
  { country: 'Equatorial Guinea', code: 'GQ', image: 'default' },
  { country: 'Greece', code: 'GR', image: 'greece' },
  { country: 'Guatemala', code: 'GT', image: 'default' },
  { country: 'Guam', code: 'GU', image: 'default' },
  { country: 'Guinea-Bissau', code: 'GW', image: 'default' },
  { country: 'Guyana', code: 'GY', image: 'default' },
  { country: 'Hong Kong', code: 'HK', image: 'hong-kong' },
  { country: 'Honduras', code: 'HN', image: 'default' },
  { country: 'Croatia', code: 'HR', image: 'croatia' },
  { country: 'Hungary', code: 'HU', image: 'hungary' },
  { country: 'Indonesia', code: 'ID', image: 'indonesia' },
  { country: 'Ireland', code: 'IE', image: 'ireland' },
  { country: 'Israel', code: 'IL', image: 'default' },
  { country: 'Isle of Man', code: 'IM', image: 'default' },
  { country: 'India', code: 'IN', image: 'india' },
  { country: 'British Indian Ocean Territory', code: 'IO', image: 'default' },
  { country: 'Iceland', code: 'IS', image: 'default' },
  { country: 'Italy', code: 'IT', image: 'italy' },
  { country: 'Jersey', code: 'JE', image: 'default' },
  { country: 'Jamaica', code: 'JM', image: 'jamaica' },
  { country: 'Jordan', code: 'JO', image: 'jordan' },
  { country: 'Japan', code: 'JP', image: 'japan' },
  { country: 'Kenya', code: 'KE', image: 'kenya' },
  { country: 'Kyrgyzstan', code: 'KG', image: 'default' },
  { country: 'Cambodia', code: 'KH', image: 'default' },
  { country: 'Kiribati', code: 'KI', image: 'default' },
  { country: 'Saint Kitts and Nevis', code: 'KN', image: 'default' },
  { country: 'South Korea', code: 'KR', image: 'default' },
  { country: 'Kuwait', code: 'KW', image: 'default' },
  { country: 'Cayman Islands', code: 'KY', image: 'default' },
  { country: 'Kazakhstan', code: 'KZ', image: 'default' },
  { country: 'Laos', code: 'LA', image: 'default' },
  { country: 'Saint Lucia', code: 'LC', image: 'default' },
  { country: 'Liechtenstein', code: 'LI', image: 'liechtenstein' },
  { country: 'Sri Lanka', code: 'LK', image: 'default' },
  { country: 'Lithuania', code: 'LT', image: 'lithuania' },
  { country: 'Luxembourg', code: 'LU', image: 'luxembourg' },
  { country: 'Latvia', code: 'LV', image: 'latvia' },
  { country: 'Morocco', code: 'MA', image: 'morocco' },
  { country: 'Monaco', code: 'MC', image: 'default' },
  { country: 'Moldova', code: 'MD', image: 'default' },
  { country: 'Montenegro', code: 'ME', image: 'default' },
  { country: 'Saint Martin', code: 'MF', image: 'default' },
  { country: 'Madagascar', code: 'MG', image: 'default' },
  { country: 'Marshall Islands', code: 'MH', image: 'default' },
  { country: 'North Macedonia', code: 'MK', image: 'default' },
  { country: 'Mali', code: 'ML', image: 'default' },
  { country: 'Mongolia', code: 'MN', image: 'default' },
  { country: 'Macau', code: 'MO', image: 'default' },
  { country: 'Northern Mariana Islands', code: 'MP', image: 'default' },
  { country: 'Martinique', code: 'MQ', image: 'default' },
  { country: 'Mauritania', code: 'MR', image: 'default' },
  { country: 'Montserrat', code: 'MS', image: 'default' },
  { country: 'Malta', code: 'MT', image: 'malta' },
  { country: 'Mauritius', code: 'MU', image: 'default' },
  { country: 'Maldives', code: 'MV', image: 'default' },
  { country: 'Malawi', code: 'MW', image: 'default' },
  { country: 'Mexico', code: 'MX', image: 'mexico' },
  { country: 'Malaysia', code: 'MY', image: 'malaysia' },
  { country: 'Mozambique', code: 'MZ', image: 'default' },
  { country: 'Namibia', code: 'NA', image: 'default' },
  { country: 'New Caledonia', code: 'NC', image: 'default' },
  { country: 'Niger', code: 'NE', image: 'default' },
  { country: 'Nicaragua', code: 'NI', image: 'default' },
  { country: 'Netherlands', code: 'NL', image: 'netherlands' },
  { country: 'Norway', code: 'NO', image: 'norway' },
  { country: 'Nepal', code: 'NP', image: 'default' },
  { country: 'Nauru', code: 'NR', image: 'default' },
  { country: 'Niue', code: 'NU', image: 'default' },
  { country: 'New Zealand', code: 'NZ', image: 'new-zealand' },
  { country: 'Oman', code: 'OM', image: 'default' },
  { country: 'Panama', code: 'PA', image: 'default' },
  { country: 'Peru', code: 'PE', image: 'default' },
  { country: 'French Polynesia', code: 'PF', image: 'default' },
  { country: 'Philippines', code: 'PH', image: 'philippine' },
  { country: 'Pakistan', code: 'PK', image: 'pakistan' },
  { country: 'Poland', code: 'PL', image: 'poland' },
  { country: 'Saint Pierre and Miquelon', code: 'PM', image: 'default' },
  { country: 'Pitcairn Islands', code: 'PN', image: 'default' },
  { country: 'Puerto Rico', code: 'PR', image: 'default' },
  { country: 'Portugal', code: 'PT', image: 'portugal' },
  { country: 'Palau', code: 'PW', image: 'default' },
  { country: 'Paraguay', code: 'PY', image: 'default' },
  { country: 'Qatar', code: 'QA', image: 'default' },
  { country: 'Réunion', code: 'RE', image: 'default' },
  { country: 'Romania', code: 'RO', image: 'romania' },
  { country: 'Serbia', code: 'RS', image: 'default' },
  { country: 'Rwanda', code: 'RW', image: 'default' },
  { country: 'Saudi Arabia', code: 'SA', image: 'default' },
  { country: 'Solomon Islands', code: 'SB', image: 'default' },
  { country: 'Seychelles', code: 'SC', image: 'default' },
  { country: 'Sweden', code: 'SE', image: 'sweden' },
  { country: 'Singapore', code: 'SG', image: 'singapore' },
  { country: 'Saint Helena', code: 'SH', image: 'default' },
  { country: 'Slovenia', code: 'SI', image: 'slovenia' },
  { country: 'Svalbard and Jan Mayen', code: 'SJ', image: 'default' },
  { country: 'Slovakia', code: 'SK', image: 'slovakia' },
  { country: 'Sierra Leone', code: 'SL', image: 'default' },
  { country: 'San Marino', code: 'SM', image: 'default' },
  { country: 'Senegal', code: 'SN', image: 'default' },
  { country: 'Suriname', code: 'SR', image: 'default' },
  { country: 'São Tomé and Príncipe', code: 'ST', image: 'default' },
  { country: 'El Salvador', code: 'SV', image: 'default' },
  { country: 'Sint Maarten', code: 'SX', image: 'default' },
  { country: 'Eswatini', code: 'SZ', image: 'default' },
  { country: 'Turks and Caicos Islands', code: 'TC', image: 'default' },
  { country: 'Chad', code: 'TD', image: 'default' },
  { country: 'Togo', code: 'TG', image: 'default' },
  { country: 'Thailand', code: 'TH', image: 'thailand' },
  { country: 'Tajikistan', code: 'TJ', image: 'default' },
  { country: 'Tokelau', code: 'TK', image: 'default' },
  { country: 'Timor-Leste', code: 'TL', image: 'default' },
  { country: 'Turkmenistan', code: 'TM', image: 'default' },
  { country: 'Tunisia', code: 'TN', image: 'default' },
  { country: 'Tonga', code: 'TO', image: 'default' },
  { country: 'Turkey', code: 'TR', image: 'turkey' },
  { country: 'Trinidad and Tobago', code: 'TT', image: 'default' },
  { country: 'Tuvalu', code: 'TV', image: 'default' },
  { country: 'Taiwan', code: 'TW', image: 'default' },
  { country: 'Tanzania', code: 'TZ', image: 'default' },
  { country: 'Ukraine', code: 'UA', image: 'default' },
  { country: 'Uganda', code: 'UG', image: 'default' },
  { country: 'U.S. Minor Outlying Islands', code: 'UM', image: 'default' },
  { country: 'United States', code: 'US', image: 'united-states-of-america' },
  { country: 'Uruguay', code: 'UY', image: 'default' },
  { country: 'Uzbekistan', code: 'UZ', image: 'default' },
  { country: 'Vatican City', code: 'VA', image: 'default' },
  { country: 'Saint Vincent and the Grenadines', code: 'VC', image: 'default' },
  { country: 'British Virgin Islands', code: 'VG', image: 'default' },
  { country: 'U.S. Virgin Islands', code: 'VI', image: 'default' },
  { country: 'Vietnam', code: 'VN', image: 'vietnam' },
  { country: 'Vanuatu', code: 'VU', image: 'default' },
  { country: 'Wallis and Futuna', code: 'WF', image: 'default' },
  { country: 'Samoa', code: 'WS', image: 'default' },
  { country: 'Kosovo', code: 'XK', image: 'default' },
  { country: 'Mayotte', code: 'YT', image: 'default' },
  { country: 'South Africa', code: 'ZA', image: 'south-africa' },
  { country: 'Zambia', code: 'ZM', image: 'default' },
  { country: 'Zimbabwe', code: 'ZW', image: 'default' }
]

/**
 * Returns countries for the active payment provider (webpack PAYMENT_PROVIDER).
 */
export function getSupportedCountryCodes(
  provider: string = (typeof process !== 'undefined' &&
    process.env &&
    process.env.PAYMENT_PROVIDER) ||
    'stripe'
): CountryOption[] {
  if (provider === 'whop') return whopCountryCodes
  return stripeCountryCodes as CountryOption[]
}

export function getSupportedCountriesCount(
  provider: string = (typeof process !== 'undefined' &&
    process.env &&
    process.env.PAYMENT_PROVIDER) ||
    'stripe'
): number {
  return getSupportedCountryCodes(provider).length
}
