version: '3.7'

services:
  backend_test:
    image: node:8.6
    command: sh -c "npm install && npm run migrate-test && npm run test"
    working_dir: /gitpay
    volumes: 
      - .:/gitpay    
    environment:
      - NODE_ENV=test
    network_mode: host
  db_test:
    image: postgres
    environment:      
      POSTGRES_DB: gitpay_test
    network_mode: host