/**
 * Provider-specific countries available for payout account onboarding.
 * Stripe list mirrors frontend country-codes (Connect-supported).
 * Whop list mirrors https://docs.whop.com/manage-your-business/manage-payouts/set-up-payouts
 */

export type SupportedCountry = {
  country: string
  code: string
}

/** Stripe Connect onboarding countries (Gitpay product list). */
export const STRIPE_SUPPORTED_COUNTRIES: SupportedCountry[] = [
  { country: 'Albania', code: 'AL' },
  { country: 'Australia', code: 'AU' },
  { country: 'Austria', code: 'AT' },
  { country: 'Belgium', code: 'BE' },
  { country: 'Brazil', code: 'BR' },
  { country: 'Bangladesh', code: 'BD' },
  { country: 'Bulgaria', code: 'BG' },
  { country: 'Canada', code: 'CA' },
  { country: 'Chile', code: 'CL' },
  { country: 'Colombia', code: 'CO' },
  { country: 'Croatia', code: 'HR' },
  { country: 'Cyprus', code: 'CY' },
  { country: 'Czech Republic', code: 'CZ' },
  { country: 'Denmark', code: 'DK' },
  { country: 'Egypt', code: 'EG' },
  { country: 'Estonia', code: 'EE' },
  { country: 'Ethiopia', code: 'ET' },
  { country: 'Finland', code: 'FI' },
  { country: 'France', code: 'FR' },
  { country: 'Germany', code: 'DE' },
  { country: 'Ghana', code: 'GH' },
  { country: 'Gibraltar', code: 'GI' },
  { country: 'Greece', code: 'GR' },
  { country: 'Hong Kong', code: 'HK' },
  { country: 'Hungary', code: 'HU' },
  { country: 'India', code: 'IN' },
  { country: 'Indonesia', code: 'ID' },
  { country: 'Ireland', code: 'IE' },
  { country: 'Italy', code: 'IT' },
  { country: 'Jamaica', code: 'JM' },
  { country: 'Japan', code: 'JP' },
  { country: 'Jordan', code: 'JO' },
  { country: 'Kenya', code: 'KE' },
  { country: 'Latvia', code: 'LV' },
  { country: 'Liechtenstein', code: 'LI' },
  { country: 'Lithuania', code: 'LT' },
  { country: 'Luxembourg', code: 'LU' },
  { country: 'Malaysia', code: 'MY' },
  { country: 'Malta', code: 'MT' },
  { country: 'Mexico', code: 'MX' },
  { country: 'Morocco', code: 'MA' },
  { country: 'Netherlands', code: 'NL' },
  { country: 'New Zealand', code: 'NZ' },
  { country: 'NG', code: 'NG' },
  { country: 'Norway', code: 'NO' },
  { country: 'Pakistan', code: 'PK' },
  { country: 'Philippines', code: 'PH' },
  { country: 'Poland', code: 'PL' },
  { country: 'Portugal', code: 'PT' },
  { country: 'Romania', code: 'RO' },
  { country: 'Singapore', code: 'SG' },
  { country: 'Slovakia', code: 'SK' },
  { country: 'Slovenia', code: 'SI' },
  { country: 'South Africa', code: 'ZA' },
  { country: 'Spain', code: 'ES' },
  { country: 'Sweden', code: 'SE' },
  { country: 'Switzerland', code: 'CH' },
  { country: 'Thailand', code: 'TH' },
  { country: 'Turkey', code: 'TR' },
  { country: 'United Arab Emirates', code: 'AE' },
  { country: 'United Kingdom', code: 'GB' },
  { country: 'United States', code: 'US' },
  { country: 'Vietnam', code: 'VN' },
]

/** Whop payout-supported countries (from Whop docs; excludes sanctioned regions). */
export const WHOP_SUPPORTED_COUNTRIES: SupportedCountry[] = [
  { country: 'Andorra', code: 'AD' },
  { country: 'United Arab Emirates', code: 'AE' },
  { country: 'Antigua and Barbuda', code: 'AG' },
  { country: 'Anguilla', code: 'AI' },
  { country: 'Albania', code: 'AL' },
  { country: 'Armenia', code: 'AM' },
  { country: 'Netherlands Antilles', code: 'AN' },
  { country: 'Angola', code: 'AO' },
  { country: 'Antarctica', code: 'AQ' },
  { country: 'Argentina', code: 'AR' },
  { country: 'American Samoa', code: 'AS' },
  { country: 'Austria', code: 'AT' },
  { country: 'Australia', code: 'AU' },
  { country: 'Aruba', code: 'AW' },
  { country: 'Azerbaijan', code: 'AZ' },
  { country: 'Bosnia and Herzegovina', code: 'BA' },
  { country: 'Barbados', code: 'BB' },
  { country: 'Bangladesh', code: 'BD' },
  { country: 'Belgium', code: 'BE' },
  { country: 'Burkina Faso', code: 'BF' },
  { country: 'Bulgaria', code: 'BG' },
  { country: 'Bahrain', code: 'BH' },
  { country: 'Benin', code: 'BJ' },
  { country: 'Saint Barthélemy', code: 'BL' },
  { country: 'Bermuda', code: 'BM' },
  { country: 'Brunei', code: 'BN' },
  { country: 'Bolivia', code: 'BO' },
  { country: 'Brazil', code: 'BR' },
  { country: 'Bahamas', code: 'BS' },
  { country: 'Bhutan', code: 'BT' },
  { country: 'Botswana', code: 'BW' },
  { country: 'Belize', code: 'BZ' },
  { country: 'Canada', code: 'CA' },
  { country: 'Cocos (Keeling) Islands', code: 'CC' },
  { country: 'Republic of the Congo', code: 'CG' },
  { country: 'Switzerland', code: 'CH' },
  { country: "Côte d'Ivoire", code: 'CI' },
  { country: 'Cook Islands', code: 'CK' },
  { country: 'Chile', code: 'CL' },
  { country: 'Cameroon', code: 'CM' },
  { country: 'China', code: 'CN' },
  { country: 'Colombia', code: 'CO' },
  { country: 'Costa Rica', code: 'CR' },
  { country: 'Cape Verde', code: 'CV' },
  { country: 'Curaçao', code: 'CW' },
  { country: 'Christmas Island', code: 'CX' },
  { country: 'Cyprus', code: 'CY' },
  { country: 'Czech Republic', code: 'CZ' },
  { country: 'Germany', code: 'DE' },
  { country: 'Djibouti', code: 'DJ' },
  { country: 'Denmark', code: 'DK' },
  { country: 'Dominica', code: 'DM' },
  { country: 'Dominican Republic', code: 'DO' },
  { country: 'Algeria', code: 'DZ' },
  { country: 'Ecuador', code: 'EC' },
  { country: 'Estonia', code: 'EE' },
  { country: 'Egypt', code: 'EG' },
  { country: 'Western Sahara', code: 'EH' },
  { country: 'Spain', code: 'ES' },
  { country: 'Ethiopia', code: 'ET' },
  { country: 'Finland', code: 'FI' },
  { country: 'Fiji', code: 'FJ' },
  { country: 'Falkland Islands', code: 'FK' },
  { country: 'Micronesia', code: 'FM' },
  { country: 'Faroe Islands', code: 'FO' },
  { country: 'France', code: 'FR' },
  { country: 'Gabon', code: 'GA' },
  { country: 'United Kingdom', code: 'GB' },
  { country: 'Grenada', code: 'GD' },
  { country: 'Georgia', code: 'GE' },
  { country: 'French Guiana', code: 'GF' },
  { country: 'Guernsey', code: 'GG' },
  { country: 'Ghana', code: 'GH' },
  { country: 'Gibraltar', code: 'GI' },
  { country: 'Greenland', code: 'GL' },
  { country: 'Gambia', code: 'GM' },
  { country: 'Guinea', code: 'GN' },
  { country: 'Guadeloupe', code: 'GP' },
  { country: 'Equatorial Guinea', code: 'GQ' },
  { country: 'Greece', code: 'GR' },
  { country: 'Guatemala', code: 'GT' },
  { country: 'Guam', code: 'GU' },
  { country: 'Guinea-Bissau', code: 'GW' },
  { country: 'Guyana', code: 'GY' },
  { country: 'Hong Kong', code: 'HK' },
  { country: 'Honduras', code: 'HN' },
  { country: 'Croatia', code: 'HR' },
  { country: 'Hungary', code: 'HU' },
  { country: 'Indonesia', code: 'ID' },
  { country: 'Ireland', code: 'IE' },
  { country: 'Israel', code: 'IL' },
  { country: 'Isle of Man', code: 'IM' },
  { country: 'India', code: 'IN' },
  { country: 'British Indian Ocean Territory', code: 'IO' },
  { country: 'Iceland', code: 'IS' },
  { country: 'Italy', code: 'IT' },
  { country: 'Jersey', code: 'JE' },
  { country: 'Jamaica', code: 'JM' },
  { country: 'Jordan', code: 'JO' },
  { country: 'Japan', code: 'JP' },
  { country: 'Kenya', code: 'KE' },
  { country: 'Kyrgyzstan', code: 'KG' },
  { country: 'Cambodia', code: 'KH' },
  { country: 'Kiribati', code: 'KI' },
  { country: 'Saint Kitts and Nevis', code: 'KN' },
  { country: 'South Korea', code: 'KR' },
  { country: 'Kuwait', code: 'KW' },
  { country: 'Cayman Islands', code: 'KY' },
  { country: 'Kazakhstan', code: 'KZ' },
  { country: 'Laos', code: 'LA' },
  { country: 'Saint Lucia', code: 'LC' },
  { country: 'Liechtenstein', code: 'LI' },
  { country: 'Sri Lanka', code: 'LK' },
  { country: 'Lithuania', code: 'LT' },
  { country: 'Luxembourg', code: 'LU' },
  { country: 'Latvia', code: 'LV' },
  { country: 'Morocco', code: 'MA' },
  { country: 'Monaco', code: 'MC' },
  { country: 'Moldova', code: 'MD' },
  { country: 'Montenegro', code: 'ME' },
  { country: 'Saint Martin', code: 'MF' },
  { country: 'Madagascar', code: 'MG' },
  { country: 'Marshall Islands', code: 'MH' },
  { country: 'North Macedonia', code: 'MK' },
  { country: 'Mali', code: 'ML' },
  { country: 'Mongolia', code: 'MN' },
  { country: 'Macau', code: 'MO' },
  { country: 'Northern Mariana Islands', code: 'MP' },
  { country: 'Martinique', code: 'MQ' },
  { country: 'Mauritania', code: 'MR' },
  { country: 'Montserrat', code: 'MS' },
  { country: 'Malta', code: 'MT' },
  { country: 'Mauritius', code: 'MU' },
  { country: 'Maldives', code: 'MV' },
  { country: 'Malawi', code: 'MW' },
  { country: 'Mexico', code: 'MX' },
  { country: 'Malaysia', code: 'MY' },
  { country: 'Mozambique', code: 'MZ' },
  { country: 'Namibia', code: 'NA' },
  { country: 'New Caledonia', code: 'NC' },
  { country: 'Niger', code: 'NE' },
  { country: 'Nicaragua', code: 'NI' },
  { country: 'Netherlands', code: 'NL' },
  { country: 'Norway', code: 'NO' },
  { country: 'Nepal', code: 'NP' },
  { country: 'Nauru', code: 'NR' },
  { country: 'Niue', code: 'NU' },
  { country: 'New Zealand', code: 'NZ' },
  { country: 'Oman', code: 'OM' },
  { country: 'Panama', code: 'PA' },
  { country: 'Peru', code: 'PE' },
  { country: 'French Polynesia', code: 'PF' },
  { country: 'Philippines', code: 'PH' },
  { country: 'Pakistan', code: 'PK' },
  { country: 'Poland', code: 'PL' },
  { country: 'Saint Pierre and Miquelon', code: 'PM' },
  { country: 'Pitcairn Islands', code: 'PN' },
  { country: 'Puerto Rico', code: 'PR' },
  { country: 'Portugal', code: 'PT' },
  { country: 'Palau', code: 'PW' },
  { country: 'Paraguay', code: 'PY' },
  { country: 'Qatar', code: 'QA' },
  { country: 'Réunion', code: 'RE' },
  { country: 'Romania', code: 'RO' },
  { country: 'Serbia', code: 'RS' },
  { country: 'Rwanda', code: 'RW' },
  { country: 'Saudi Arabia', code: 'SA' },
  { country: 'Solomon Islands', code: 'SB' },
  { country: 'Seychelles', code: 'SC' },
  { country: 'Sweden', code: 'SE' },
  { country: 'Singapore', code: 'SG' },
  { country: 'Saint Helena', code: 'SH' },
  { country: 'Slovenia', code: 'SI' },
  { country: 'Svalbard and Jan Mayen', code: 'SJ' },
  { country: 'Slovakia', code: 'SK' },
  { country: 'Sierra Leone', code: 'SL' },
  { country: 'San Marino', code: 'SM' },
  { country: 'Senegal', code: 'SN' },
  { country: 'Suriname', code: 'SR' },
  { country: 'São Tomé and Príncipe', code: 'ST' },
  { country: 'El Salvador', code: 'SV' },
  { country: 'Sint Maarten', code: 'SX' },
  { country: 'Eswatini', code: 'SZ' },
  { country: 'Turks and Caicos Islands', code: 'TC' },
  { country: 'Chad', code: 'TD' },
  { country: 'Togo', code: 'TG' },
  { country: 'Thailand', code: 'TH' },
  { country: 'Tajikistan', code: 'TJ' },
  { country: 'Tokelau', code: 'TK' },
  { country: 'Timor-Leste', code: 'TL' },
  { country: 'Turkmenistan', code: 'TM' },
  { country: 'Tunisia', code: 'TN' },
  { country: 'Tonga', code: 'TO' },
  { country: 'Turkey', code: 'TR' },
  { country: 'Trinidad and Tobago', code: 'TT' },
  { country: 'Tuvalu', code: 'TV' },
  { country: 'Taiwan', code: 'TW' },
  { country: 'Tanzania', code: 'TZ' },
  { country: 'Ukraine', code: 'UA' },
  { country: 'Uganda', code: 'UG' },
  { country: 'U.S. Minor Outlying Islands', code: 'UM' },
  { country: 'United States', code: 'US' },
  { country: 'Uruguay', code: 'UY' },
  { country: 'Uzbekistan', code: 'UZ' },
  { country: 'Vatican City', code: 'VA' },
  { country: 'Saint Vincent and the Grenadines', code: 'VC' },
  { country: 'British Virgin Islands', code: 'VG' },
  { country: 'U.S. Virgin Islands', code: 'VI' },
  { country: 'Vietnam', code: 'VN' },
  { country: 'Vanuatu', code: 'VU' },
  { country: 'Wallis and Futuna', code: 'WF' },
  { country: 'Samoa', code: 'WS' },
  { country: 'Kosovo', code: 'XK' },
  { country: 'Mayotte', code: 'YT' },
  { country: 'South Africa', code: 'ZA' },
  { country: 'Zambia', code: 'ZM' },
  { country: 'Zimbabwe', code: 'ZW' },
]

export function getSupportedCountriesForProvider(
  provider: string = 'stripe'
): SupportedCountry[] {
  if (provider === 'whop') return [...WHOP_SUPPORTED_COUNTRIES]
  return [...STRIPE_SUPPORTED_COUNTRIES]
}
