require('../../models')

const routerAuth = require('./routes/auth')
const routerProject = require('./routes/projects')
const routerTask = require('./routes/tasks')
const routerTeam = require('./routes/team')
const routerOrder = require('./routes/orders')
const routerWebhook = require('./routes/webhooks')
const routerInfo = require('./routes/info')
const routerOrganization = require('./routes/organization')
const routerContact = require('./routes/contact')
const routerTypes = require('./routes/types')
const routerTaskSolution = require('./routes/taskSolutions')
const routerCoupon = require('./routes/coupon')
const routerLabel = require('./routes/label')
const routerOffer = require('./routes/offer')

exports.init = (app) => {
  app.use('/', routerAuth)
  app.use('/tasks', routerTask)
  app.use('/projects', routerProject)
  app.use('/team', routerTeam)
  app.use('/orders', routerOrder)
  app.use('/webhooks', routerWebhook)
  app.use('/info', routerInfo)
  app.use('/organizations', routerOrganization)
  app.use('/types', routerTypes)
  app.use('/contact', routerContact)
  app.use('/tasksolutions', routerTaskSolution)
  app.use('/coupon', routerCoupon)
  app.use('/labels', routerLabel)
  app.use('/offers', routerOffer)
}
