export const countryCodes = [
    { country: 'Australia', code: 'AU', image: 'australia' },
    { country: 'Austria', code: 'AT', image: 'austria' },
    { country: 'Belgium', code: 'BE', image: 'belgium' },
    { country: 'Brazil ', code: 'BR', image: 'brazil' },
    { country: 'Canada', code: 'CA', image: 'canada' },
    { country: 'Denmark', code: 'DK', image: 'denmark' },
    { country: 'Finland', code: 'FI', image: 'finland' },
    { country: 'France', code: 'FR', image: 'france' },
    { country: 'Germany', code: 'DE', image: 'germany' },
    { country: 'Hong Kong', code: 'HK', image: 'hong-kong' },
    { country: 'Ireland', code: 'IE', image: 'ireland' },
    { country: 'Japan', code: 'JP', image: 'japan' },
    { country: 'Luxembourg', code: 'LU', image: 'luxembourg' },
    { country: 'Mexico ', code: 'MX', image: 'mexico' },
    { country: 'Netherlands', code: 'NL', image: 'netherlands' },
    { country: 'New Zealand', code: 'NZ', image: 'new-zealand' },
    { country: 'Nigeria', code: 'NG', image: 'nigeria' },
    { country: 'Norway', code: 'NO', image: 'norway' },
    { country: 'Romania', code: 'RO', image: 'romania' },
    { country: 'Singapore', code: 'SG', image: 'singapore' },
    { country: 'Spain', code: 'ES', image: 'spain' },
    { country: 'Sweden', code: 'SE', image: 'sweden' },
    { country: 'Switzerland', code: 'CH', image: 'switzerland' },
    { country: 'United Kingdom', code: 'GB', image: 'united-kingdom' },
    { country: 'United States', code: 'US', image: 'united-states-of-america' },
    { country: 'Italy', code: 'IT', image: 'italy' },
    { country: 'Portugal', code: 'PT', image: 'portugal' },
  ]