export const countryCodes = [
  { country: 'Australia', code: 'AU', image: 'australia' },
  { country: 'Austria', code: 'AT', image: 'austria' },
  { country: 'Belgium', code: 'BE', image: 'belgium' },
  { country: 'Brazil ', code: 'BR', image: 'brazil' },
  { country: 'Bulgaria', code: 'BG', image: 'bulgaria' },
  { country: 'Canada', code: 'CA', image: 'canada' },
  { country: 'Croatia', code: 'HR', image: 'croatia' },
  { country: 'Cyprus', code: 'CY', image: 'cyprus' },
  { country: 'Czech Republic', code: 'CZ', image: 'czech-republic' },
  { country: 'Denmark', code: 'DK', image: 'denmark' },
  { country: 'Estonia', code: 'EE', image: 'estonia' },
  { country: 'Finland', code: 'FI', image: 'finland' },
  { country: 'France', code: 'FR', image: 'france' },
  { country: 'Germany', code: 'DE', image: 'germany' },
  { country: 'Ghana', code: 'GH', image: 'ghana' },
  { country: 'Gibraltar', code: 'GI', image: 'gibraltar' },
  { country: 'Greece', code: 'GR', image: 'greece' },
  { country: 'Hong Kong', code: 'HK', image: 'hong-kong' },
  { country: 'Hungary', code: 'HU', image: 'hungary' },
  { country: 'India', code: 'IN', image: 'india' },
  // { country: 'Indonesia', code: 'ID', image: 'indonesia'}, invite only
  { country: 'Ireland', code: 'IE', image: 'ireland' },
  { country: 'Italy', code: 'IT', image: 'italy' },
  { country: 'Japan', code: 'JP', image: 'japan' },
  { country: 'Kenya', code: 'KE', image: 'kenya' },
  { country: 'Latvia', code: 'LV', image: 'latvia' },
  { country: 'Liechtenstein', code: 'LI', image: 'liechtenstein' },
  { country: 'Lithuania', code: 'LT', image: 'lithuania' },
  { country: 'Luxembourg', code: 'LU', image: 'luxembourg' },
  { country: 'Malaysia', code: 'MY', image: 'malaysia' },
  { country: 'Malta', code: 'MT', image: 'malta' },
  { country: 'Mexico ', code: 'MX', image: 'mexico' },
  { country: 'Netherlands', code: 'NL', image: 'netherlands' },
  { country: 'New Zealand', code: 'NZ', image: 'new-zealand' },
  { country: 'Nigeria', code: 'NG', image: 'nigeria' },
  { country: 'Norway', code: 'NO', image: 'norway' },
  { country: 'Poland', code: 'PL', image: 'poland' },
  { country: 'Portugal', code: 'PT', image: 'portugal' },
  { country: 'Romania', code: 'RO', image: 'romania' },
  { country: 'Singapore', code: 'SG', image: 'singapore' },
  { country: 'Slovakia', code: 'SK', image: 'slovakia' },
  { country: 'Slovenia', code: 'SI', image: 'slovenia' },
  { country: 'South Africa', code: 'ZA', image: 'south-africa' },
  { country: 'Spain', code: 'ES', image: 'spain' },
  { country: 'Sweden', code: 'SE', image: 'sweden' },
  { country: 'Switzerland', code: 'CH', image: 'switzerland' },
  { country: 'Thailand', code: 'TH', image: 'thailand' },
  { country: 'United Arab Emirates', code: 'AE', image: 'united-arab-emirates' },
  { country: 'United Kingdom', code: 'GB', image: 'united-kingdom' },
  { country: 'United States', code: 'US', image: 'united-states-of-america' }
]
