export default {
    API_URL: process.env.API_HOST,
    ACCOUNT_FIELDS: {
      'external_account': 'Conta bancária',
      'legal_entity.address.city': 'Cidade',
      'legal_entity.address.line1': 'Primeira parte do endereço',
      'legal_entity.address.postal_code': 'CEP',
      'legal_entity.address.state': 'Estado',
      'legal_entity.dob.day': 'Dia do nascimento',
      'legal_entity.dob.month': 'Mês do nascimento',
      'legal_entity.dob.year': 'Ano do nascimento',
      'legal_entity.first_name': 'Primeiro nome',
      'legal_entity.last_name': 'Último nome',
      'legal_entity.personal_id_number': 'Número de identificação',
      'legal_entity.verification.document': 'Documento de identificação',
      'legal_entity.type': 'Tipo de identificação (identidade ou CPF',
      'tos_acceptance.date': 'Data da confirmação dos termos de uso',
      'tos_acceptance.ip': 'Aceitar os termos de uso'
    },
    ACCOUNT_REASONS: {
      'fields_needed': 'Pendente de verificação',
    },
    STATUSES: {
      'open': 'Aberta',
      'OPEN': 'Aberta',
      'in_progress': 'Em desenvolvimento',
      'closed': 'Finalizada',
      '': 'Status indefinido',
      null: 'Status indefinido',
      undefined: 'Status indefinido'
    },

    BANK_NUMBERS: {
      '110': 'BANCO PARA TESTE STRIPE',
      '001': 'BANCO DO BRASIL S.A. (Banco do Brasil)',
      '237': 'BANCO BRADESCO S.A. (Bradesco)',
      '341': 'BANCO ITAU S.A. (Itaú)',
      '356': 'BANCO ABN AMRO REAL S.A. (Real)',
      '409': 'UNIBANCO UNIAO DE BANCOS BRASILEIROS S.A. (Unibanco)',
      '041': 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (Banrisul)',
      '104': 'CAIXA ECONOMICA FEDERAL (Caixa Econômica Federal)',
      '033': 'BANCO SANTANDER S.A. (Santander Banespa)',
      '399': 'HSBC BANK BRASIL S.A.BANCO MULTIPLO (HSBC)',
      '745': 'BANCO CITIBANK S.A.',
      '151': 'BANCO NOSSA CAIXA S.A (Nossa Caixa)',
      '389': 'BANCO MERCANTIL DO BRASIL S.A. (Mercantil do Brasil)',
      '004': 'BANCO DO NORDESTE DO BRASIL S.A (Banco do Nordeste (BNB) )',
      '021': 'BANESTES S.A BANCO DO ESTADO DO ESPIRITO SANTO (Banestes)',
      '422': 'BANCO SAFRA S.A. (Safra)',
      '003': 'BANCO DA AMAZONIA S.A. (Banco da Amazônia (Basa))',
      '047': 'Banco do Estado de Sergipe S.A (Banese)',
      '070': 'Banco de Brasília S.A. (BRB)',
      '655': 'Banco Votorantim S.A (Votorantim)',
      '107': 'Banco BBM S.A (BBM)',
      '025': 'Banco Alfa S.A (Alfa)',
      '263': 'Banco Cacique S. A. (Cacique)',
      '229': 'BANCO CRUZEIRO DO SUL S.A. (Cruzeiro do Sul)',
      '252': 'BANCO FININVEST S.A. (Fininvest)',
      '063': 'BANCO IBI S.A - BANCO MULTIPLO (Banco IBI)',
      '623': 'BANCO PANAMERICANO S.A. (PanAmericano)',
      '633': 'BANCO RENDIMENTO S.A. (Banco Rendimento)',
      '749': 'BANCO SIMPLES S.A. (Banco Simples)',
      '215': 'BANCO ACOMERCIAL E DE INVESTIMENTO SUDAMERIS S.A. (Sudameris)',
      '756': 'BANCO COOPERATIVO DO BRASIL S.A. - (BANCOOB)',
      '748': 'BANCO COOPERATIVO SICREDI S.A. (SICREDI)',
      '065': 'LEMON BANK BANCO MÚLTIPLO S..A (Lemon Bank)',
      '069': 'BPN BRASIL BANCO MÚLTIPLO S.A. (BPN)',
      '719': 'BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A. (Banif)',
      '318': 'BANCO BMG S.A. (BMG)',
      '027': 'BANCO DO ESTADO DE SANTA CATARINA S.A.',
      '208': 'BANCO UBS PACTUAL S.A.',
      '479': 'BANCO ITAUBANK S.A.',
      '077': 'BANCO INTERMEDIUM S.A.',
      '212': 'BANCO ORIGINAL',
      '085': 'CECRED-COOPERATIVA CENTRAL DE CREDITO URBANO'
    }
}
