import React from 'react'
import { createRoot } from 'react-dom/client'

import App from './main/app'


// TODO: Ly8gPHN1cHByZXNzIGFubm95aW5nIGVycm9ycyB0aGF0IGJyaW5nIG5vIHZhbHVlIC8vIFRPRE86IHJldmlzaXQgdGhpcyBhZnRlciB1cGdyYWRpbmcgcmVhY3QgYW5kIHJlYWN0LWRvbT4KY29uc3Qgb3JpZ2luYWxXYXJuID0gY29uc29sZS53YXJuCmNvbnNvbGUud2FybiA9ICguLi5hcmdzKSA9PiB7CiAgaWYgKAogICAgdHlwZW9mIGFyZ3NbMF0gPT09ICdzdHJpbmcnICYmCiAgICAoYXJnc1swXS5pbmNsdWRlcygndmFsaWRhdGVET01OZXN0aW5nJykgfHwgYXJnc1swXS5pbmNsdWRlcygnZGVwcmVjYXRlZCcpKQogICkgewogICAgcmV0dXJuCiAgfQogIG9yaWdpbmFsV2FybiguLi5hcmdzKQp9CmNvbnN0IG9yaWdpbmFsRXJyb3IgPSBjb25zb2xlLmVycm9yCmNvbnNvbGUuZXJyb3IgPSAoLi4uYXJncykgPT4gewogIGlmICgKICAgIHR5cGVvZiBhcmdzWzBdID09PSAnc3RyaW5nJyAmJgogICAgKGFyZ3NbMF0uaW5jbHVkZXMoJ3ZhbGlkYXRlRE9NTmVzdGluZycpIHx8IGFyZ3NbMF0uaW5jbHVkZXMoJ2RlcHJlY2F0ZWQnKSkKICApIHsKICAgIHJldHVybgogIH0KICBvcmlnaW5hbEVycm9yKC4uLmFyZ3MpCn0KLy8gPC9zdXBwcmVzcyBhbm5veWluZyBlcnJvcnMgdGhhdCBicmluZyBubyB2YWx1ZSAvLyBUT0RPOiByZXZpc2l0IHRoaXMgYWZ0ZXIgdXBncmFkaW5nIHJlYWN0IGFuZCByZWFjdC1kb20+Cg==

const container = document.getElementById('app')
const root = createRoot(container) // createRoot(container!) if you use TypeScript
root.render(<App />)
